#CLASS_TYPES = ['BPSK', 'QPSK', '8PSK', 'PAM4', 'QAM16', 'QAM64', 'GFSK', 'CPFSK', 'WBFM', 'AM-DSB', 'AM-SSB']
CLASS_TYPES = ['QAM4', 'QAM16','QAM64','QAM256','PSK2','PSK4','PSK8','PSK16']
NUM_CLASS = len(CLASS_TYPES)

# Same notation as paper
C_CLASS = NUM_CLASS
S_GRID = 7
B_BOXES = 2

# Image parameters
IMG_H = 128
IMG_W = 128

LAMBDA_OBJ = 1
LAMBDA_NOOBJ = 0.5
CLASS_SCALE = 10
COORD_SCALE = 5
CONF_THRESH = 0.5
